services:
  - type: web
    name: live-train-tracker
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: API_KEY
        sync: false
